- name: nginx install ands run
  hosts: web
  become: yes #sudo access
  tasks:
  - name: install nginx
    ansible.builtin.package:  # it will work for all diste os
      name: nginx
      state: present