-name: variables to print
 hosts: web
 vars: #play level, all task level in this play have access to this
   COURSE: "DevOps with AWS"
   DURATION: "120 HRS"
   TRAINER: "Anjaneya Reddy M"
 tasks:
 - name: print the information
   ansible.builtin.debug:
     msg: "Hi, I am Leanring {{COURSE}}, Duration is :{{DURATION}}, trainer is {{TRAINER}}"  

 - name: print the information again 
   ansible.builtin.debug:
     msg: "Hi, I am Leanring {{COURSE}}, Duration is :{{DURATION}}, trainer is {{TRAINER}}"  
    