- name: varibles from files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the course information
    ansible.buildin.debug:
        msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"
  tasks:
  - name: print the  information     
     ansible.buildin.debug:
         msg: "Hi, I am learning {{COURSE}}, Duration is: {{DURATION}}, Trainer: {{TRAINER}}"