- name: varibles from files
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the course information
    ansible.buildin.debug:
       msg: "Hi, I am learning {{COURCE}}, Duration is :{{DURATION}}"