- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: Please enter the course name
    private: false #not confidentials
  - name: DURATION
    prompt: Please enter the duration
    private: false
  tasks:
  - name: print the cource information
    ansible.builtin.debug:
      msg: "Hi, I am learning {{COURSE}},Duration is: {{DURATION}}, Trainer: {{TRAINER}}"  