- name: check a number is lessthan 10 or not
  hosts: local
  connection: local
  vars_prompt:
  - name: test_number
    prompt : Please enter the number
    private : false
  tasks:
  - name: print this if lessthan 10
    ansible.builtin.debug:
      msg: "Given number {{ test_number }}   is less than 10"
    when: test_number | int < 10 
  - name: print this if grtterthan 10
    ansible.builtin.debug:
      msg: "Given number {{ test_number }}   is less than 10"
    when: test_number | int  >= 10    

