- name: loops demo
  hosts: local
  become: yes
  connection: local
  tasks:
  - name: install package
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.state }} "
    loop:
    - { name: 'mysql', state: 'absent'}  
