- name:  demo on filters/funtions
  hosts: local
  connection: local
  tasks:
   - name: print course
     ansible.builtin.debug:
        msg: " Hello {{ course | default('Ansible')}}"

   - name: Convert to upper case
     vars:
       greeting: "Hello Ramesh"
     ansible.builtin.debug:
        msg: " Hello {{ greeting | upper }}"    


   - name: get the unique value
     vars:
        numbers: [1,2,3,4,5,5,4,1]
     ansible.builtin.debug:
        msg: "Unique numbers {{ numbers | unique }}  ""
